//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    
    public partial class ProvinceList
    {
        public int ProvinceID { get; set; }
        public string Alias { get; set; }
        public string Province { get; set; }
    }
}
