//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RAMEntities : DbContext
    {
        public RAMEntities()
            : base("name=RAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory_by_SId(Nullable<int> sID, string lang, string token)
        {
            var sIDParameter = sID.HasValue ?
                new ObjectParameter("SID", sID) :
                new ObjectParameter("SID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory_by_SId", sIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubCategoryResult> Proc_Get_SubCategory_byTopCategory(Nullable<int> tID, string lang, string token)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubCategoryResult>("Proc_Get_SubCategory_byTopCategory", tIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<TopCategoryList> Proc_Get_TopCategory(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopCategoryList>("Proc_Get_TopCategory", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<TopCategoryList> Proc_TopCategory_by_ID(Nullable<int> tID, string lANG, string token)
        {
            var tIDParameter = tID.HasValue ?
                new ObjectParameter("TID", tID) :
                new ObjectParameter("TID", typeof(int));
    
            var lANGParameter = lANG != null ?
                new ObjectParameter("LANG", lANG) :
                new ObjectParameter("LANG", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopCategoryList>("Proc_TopCategory_by_ID", tIDParameter, lANGParameter, tokenParameter);
        }
    
        public virtual ObjectResult<CityList> AllCitiesList(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityList>("AllCitiesList", tokenParameter);
        }
    
        public virtual ObjectResult<CityList> GetCityByProvince(Nullable<int> pid, string token)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityList>("GetCityByProvince", pidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<CityResult> Get_City_By_CId(Nullable<int> cid, string token)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityResult>("Get_City_By_CId", cidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<ProvinceList> getProvinceByID(string lang, Nullable<int> pid, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProvinceList>("getProvinceByID", langParameter, pidParameter, tokenParameter);
        }
    
        public virtual ObjectResult<ProvinceList> getProvinceList(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProvinceList>("getProvinceList", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Cluster_Search_Keywords(string searchWordS, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Cluster_Search_Keywords", searchWordSParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_RamResource_by_Lang(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_RamResource_by_Lang", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_RamResource(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_RamResource", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_City(Nullable<int> cityID, string lang, string token)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_City", cityIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_ID(Nullable<int> id, string lang, string token)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_ID", idParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Province(Nullable<int> provinceID, string lang, string token)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Province", provinceIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Province_and_City(Nullable<int> cityID, Nullable<int> provinceID, string lang)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Province_and_City", cityIDParameter, provinceIDParameter, langParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_SubCategory(Nullable<int> subCategoryID, string lang, string token)
        {
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_SubCategory", subCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Top_and_SubCategory(Nullable<int> tOPCategoryID, Nullable<int> subCategoryID, string lang)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Top_and_SubCategory", tOPCategoryIDParameter, subCategoryIDParameter, langParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_TopCategory(Nullable<int> tOPCategoryID, string lang, string token)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_TopCategory", tOPCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SuggestionWords> Proc_Get_SuggestionWord_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestionWords>("Proc_Get_SuggestionWord_List");
        }
    
        public virtual ObjectResult<SuggestionWords> Proc_Increment_Suggestion_Word(string l)
        {
            var lParameter = l != null ?
                new ObjectParameter("L", l) :
                new ObjectParameter("L", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SuggestionWords>("Proc_Increment_Suggestion_Word", lParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_Resource_In_Radius_boundary_Box(Nullable<decimal> lat, Nullable<decimal> @long, Nullable<decimal> radius, string lang, string token)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_Resource_In_Radius_boundary_Box", latParameter, longParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_All_Resources_In_Radius(Nullable<decimal> startLatitude, Nullable<decimal> startLongitude, Nullable<decimal> radius, string lang, string token)
        {
            var startLatitudeParameter = startLatitude.HasValue ?
                new ObjectParameter("StartLatitude", startLatitude) :
                new ObjectParameter("StartLatitude", typeof(decimal));
    
            var startLongitudeParameter = startLongitude.HasValue ?
                new ObjectParameter("StartLongitude", startLongitude) :
                new ObjectParameter("StartLongitude", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_All_Resources_In_Radius", startLatitudeParameter, startLongitudeParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Cluster_Search_Short(string searchWordS, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Cluster_Search_Short", searchWordSParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resources_In_Radius(Nullable<decimal> startLatitude, Nullable<decimal> startLongitude, Nullable<decimal> radius, string lang, string token)
        {
            var startLatitudeParameter = startLatitude.HasValue ?
                new ObjectParameter("StartLatitude", startLatitude) :
                new ObjectParameter("StartLatitude", typeof(decimal));
    
            var startLongitudeParameter = startLongitude.HasValue ?
                new ObjectParameter("StartLongitude", startLongitude) :
                new ObjectParameter("StartLongitude", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resources_In_Radius", startLatitudeParameter, startLongitudeParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_In_Radius_boundary_Box(Nullable<decimal> lat, Nullable<decimal> @long, Nullable<decimal> radius, string lang, string token)
        {
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("Long", @long) :
                new ObjectParameter("Long", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_In_Radius_boundary_Box", latParameter, longParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_City(Nullable<int> cityID, string lang, string token)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_City", cityIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_Province(Nullable<int> provinceID, string lang, string token)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_Province", provinceIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_SubCategory(Nullable<int> subCategoryID, string lang, string token)
        {
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_SubCategory", subCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_by_TopCategory(Nullable<int> tOPCategoryID, string lang, string token)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_by_TopCategory", tOPCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Unique_Resource(string map, string resourceAgencyNum, Nullable<int> subcategoryid, Nullable<int> topcategoryid, string lang, string token)
        {
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            var resourceAgencyNumParameter = resourceAgencyNum != null ?
                new ObjectParameter("resourceAgencyNum", resourceAgencyNum) :
                new ObjectParameter("resourceAgencyNum", typeof(string));
    
            var subcategoryidParameter = subcategoryid.HasValue ?
                new ObjectParameter("subcategoryid", subcategoryid) :
                new ObjectParameter("subcategoryid", typeof(int));
    
            var topcategoryidParameter = topcategoryid.HasValue ?
                new ObjectParameter("topcategoryid", topcategoryid) :
                new ObjectParameter("topcategoryid", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Unique_Resource", mapParameter, resourceAgencyNumParameter, subcategoryidParameter, topcategoryidParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_By_Coverage(string s, string lang, string token)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_By_Coverage", sParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Search_Result> Proc_Search_Resource_By_Coverage(string s, string lang, string token)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Result>("Proc_Search_Resource_By_Coverage", sParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<string> Proc_Get_Allow_Domain()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Get_Allow_Domain");
        }
    
        public virtual ObjectResult<string> Proc_Get_Allow_IP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Get_Allow_IP");
        }
    
        public virtual ObjectResult<GoogleCityList> Proc_Get_Google_All_City()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GoogleCityList>("Proc_Get_Google_All_City");
        }
    
        public virtual ObjectResult<GoogleCityList> Proc_Get_Google_City_By_GoogleCityID(Nullable<int> cid)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GoogleCityList>("Proc_Get_Google_City_By_GoogleCityID", cidParameter);
        }
    
        public virtual ObjectResult<GoogleCityList> Proc_Get_Google_City_By_ProvinceID(Nullable<int> pID)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("PID", pID) :
                new ObjectParameter("PID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GoogleCityList>("Proc_Get_Google_City_By_ProvinceID", pIDParameter);
        }
    
        public virtual ObjectResult<GoogleCityList> Proc_Increment_Google_City(string l)
        {
            var lParameter = l != null ?
                new ObjectParameter("L", l) :
                new ObjectParameter("L", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GoogleCityList>("Proc_Increment_Google_City", lParameter);
        }
    
        public virtual ObjectResult<CityList> Proc_Increment_Loaction_Search(string token, string l)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("L", l) :
                new ObjectParameter("L", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CityList>("Proc_Increment_Loaction_Search", tokenParameter, lParameter);
        }
    
        public virtual ObjectResult<string> Proc_Get_Blocked_IP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Get_Blocked_IP");
        }
    
        public virtual ObjectResult<RamResource> Proc_Get_Resource_by_Classification(string type, string lang, string token)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RamResource>("Proc_Get_Resource_by_Classification", typeParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<geolocation> Proc_Get_Canadaip(Nullable<long> ip, string token)
        {
            var ipParameter = ip.HasValue ?
                new ObjectParameter("ip", ip) :
                new ObjectParameter("ip", typeof(long));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<geolocation>("Proc_Get_Canadaip", ipParameter, tokenParameter);
        }
    
        public virtual int Proc_apilog(string dbschema, string csmethod, string format, string para, string lang, string token, string cscontent, string csendpoint, string keywords, string csip, string csstatus, Nullable<int> cscode, string cshost, string csurl, string csuseragent)
        {
            var dbschemaParameter = dbschema != null ?
                new ObjectParameter("dbschema", dbschema) :
                new ObjectParameter("dbschema", typeof(string));
    
            var csmethodParameter = csmethod != null ?
                new ObjectParameter("csmethod", csmethod) :
                new ObjectParameter("csmethod", typeof(string));
    
            var formatParameter = format != null ?
                new ObjectParameter("format", format) :
                new ObjectParameter("format", typeof(string));
    
            var paraParameter = para != null ?
                new ObjectParameter("para", para) :
                new ObjectParameter("para", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var cscontentParameter = cscontent != null ?
                new ObjectParameter("cscontent", cscontent) :
                new ObjectParameter("cscontent", typeof(string));
    
            var csendpointParameter = csendpoint != null ?
                new ObjectParameter("csendpoint", csendpoint) :
                new ObjectParameter("csendpoint", typeof(string));
    
            var keywordsParameter = keywords != null ?
                new ObjectParameter("keywords", keywords) :
                new ObjectParameter("keywords", typeof(string));
    
            var csipParameter = csip != null ?
                new ObjectParameter("csip", csip) :
                new ObjectParameter("csip", typeof(string));
    
            var csstatusParameter = csstatus != null ?
                new ObjectParameter("csstatus", csstatus) :
                new ObjectParameter("csstatus", typeof(string));
    
            var cscodeParameter = cscode.HasValue ?
                new ObjectParameter("cscode", cscode) :
                new ObjectParameter("cscode", typeof(int));
    
            var cshostParameter = cshost != null ?
                new ObjectParameter("cshost", cshost) :
                new ObjectParameter("cshost", typeof(string));
    
            var csurlParameter = csurl != null ?
                new ObjectParameter("csurl", csurl) :
                new ObjectParameter("csurl", typeof(string));
    
            var csuseragentParameter = csuseragent != null ?
                new ObjectParameter("csuseragent", csuseragent) :
                new ObjectParameter("csuseragent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_apilog", dbschemaParameter, csmethodParameter, formatParameter, paraParameter, langParameter, tokenParameter, cscontentParameter, csendpointParameter, keywordsParameter, csipParameter, csstatusParameter, cscodeParameter, cshostParameter, csurlParameter, csuseragentParameter);
        }
    
        public virtual int Proc_Insert_Answer(string token, Nullable<int> surveyQuestion_ID, Nullable<int> chatID, string surveyAnswer, string language, string surveyAnswer_Device)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var surveyQuestion_IDParameter = surveyQuestion_ID.HasValue ?
                new ObjectParameter("surveyQuestion_ID", surveyQuestion_ID) :
                new ObjectParameter("surveyQuestion_ID", typeof(int));
    
            var chatIDParameter = chatID.HasValue ?
                new ObjectParameter("chatID", chatID) :
                new ObjectParameter("chatID", typeof(int));
    
            var surveyAnswerParameter = surveyAnswer != null ?
                new ObjectParameter("surveyAnswer", surveyAnswer) :
                new ObjectParameter("surveyAnswer", typeof(string));
    
            var languageParameter = language != null ?
                new ObjectParameter("language", language) :
                new ObjectParameter("language", typeof(string));
    
            var surveyAnswer_DeviceParameter = surveyAnswer_Device != null ?
                new ObjectParameter("surveyAnswer_Device", surveyAnswer_Device) :
                new ObjectParameter("surveyAnswer_Device", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_Insert_Answer", tokenParameter, surveyQuestion_IDParameter, chatIDParameter, surveyAnswerParameter, languageParameter, surveyAnswer_DeviceParameter);
        }
    
        public virtual ObjectResult<Proc_GetSurveyQuestionByQuestionID_Result> Proc_GetSurveyQuestionByQuestionID(string token, Nullable<int> qid, string lang)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var qidParameter = qid.HasValue ?
                new ObjectParameter("qid", qid) :
                new ObjectParameter("qid", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetSurveyQuestionByQuestionID_Result>("Proc_GetSurveyQuestionByQuestionID", tokenParameter, qidParameter, langParameter);
        }
    
        public virtual ObjectResult<Proc_GetSurveyQuestionOptsByQuestionID_Result> Proc_GetSurveyQuestionOptsByQuestionID(string token, Nullable<int> qid, string lang)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var qidParameter = qid.HasValue ?
                new ObjectParameter("qid", qid) :
                new ObjectParameter("qid", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetSurveyQuestionOptsByQuestionID_Result>("Proc_GetSurveyQuestionOptsByQuestionID", tokenParameter, qidParameter, langParameter);
        }
    
        public virtual ObjectResult<Proc_GetSurveyTypeByID_Result> Proc_GetSurveyTypeByID(string token, Nullable<int> sid, string lang)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetSurveyTypeByID_Result>("Proc_GetSurveyTypeByID", tokenParameter, sidParameter, langParameter);
        }
    
        public virtual ObjectResult<Proc_GetSurveyQuestionByVersion_Result> Proc_GetSurveyQuestionByVersion(string token, string ver, string lang)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var verParameter = ver != null ?
                new ObjectParameter("ver", ver) :
                new ObjectParameter("ver", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetSurveyQuestionByVersion_Result>("Proc_GetSurveyQuestionByVersion", tokenParameter, verParameter, langParameter);
        }
    
        public virtual ObjectResult<Proc_GetSurveyQuestionOptsByVersion_Result> Proc_GetSurveyQuestionOptsByVersion(string token, string ver, string lang)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var verParameter = ver != null ?
                new ObjectParameter("ver", ver) :
                new ObjectParameter("ver", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetSurveyQuestionOptsByVersion_Result>("Proc_GetSurveyQuestionOptsByVersion", tokenParameter, verParameter, langParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_All_SubRamResource_by_Lang(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_All_SubRamResource_by_Lang", langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Search_Sub_Resource_In_circular_by_kws(string searchWordS, Nullable<decimal> startLatitude, Nullable<decimal> startLongitude, Nullable<decimal> radius, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var startLatitudeParameter = startLatitude.HasValue ?
                new ObjectParameter("StartLatitude", startLatitude) :
                new ObjectParameter("StartLatitude", typeof(decimal));
    
            var startLongitudeParameter = startLongitude.HasValue ?
                new ObjectParameter("StartLongitude", startLongitude) :
                new ObjectParameter("StartLongitude", typeof(decimal));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("Radius", radius) :
                new ObjectParameter("Radius", typeof(decimal));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Search_Sub_Resource_In_circular_by_kws", searchWordSParameter, startLatitudeParameter, startLongitudeParameter, radiusParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_SubCategory(Nullable<int> subCategoryID, string lang, string token)
        {
            var subCategoryIDParameter = subCategoryID.HasValue ?
                new ObjectParameter("SubCategoryID", subCategoryID) :
                new ObjectParameter("SubCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_SubCategory", subCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_TopCategory(Nullable<int> tOPCategoryID, string lang, string token)
        {
            var tOPCategoryIDParameter = tOPCategoryID.HasValue ?
                new ObjectParameter("TOPCategoryID", tOPCategoryID) :
                new ObjectParameter("TOPCategoryID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_TopCategory", tOPCategoryIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<string> Proc_Construct_APIlogKeywords_by_ETLLoadid(Nullable<int> eTLLoadID)
        {
            var eTLLoadIDParameter = eTLLoadID.HasValue ?
                new ObjectParameter("ETLLoadID", eTLLoadID) :
                new ObjectParameter("ETLLoadID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Proc_Construct_APIlogKeywords_by_ETLLoadid", eTLLoadIDParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_By_Coverage(string s, string lang, string token)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_By_Coverage", sParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_City(Nullable<int> cityID, string lang, string token)
        {
            var cityIDParameter = cityID.HasValue ?
                new ObjectParameter("CityID", cityID) :
                new ObjectParameter("CityID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_City", cityIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_Province(Nullable<int> provinceID, string lang, string token)
        {
            var provinceIDParameter = provinceID.HasValue ?
                new ObjectParameter("ProvinceID", provinceID) :
                new ObjectParameter("ProvinceID", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_Province", provinceIDParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_Phone(string phone, string lang, string token)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_Phone", phoneParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Cluster_Search_SubResource(string searchWordS, string lang, string token)
        {
            var searchWordSParameter = searchWordS != null ?
                new ObjectParameter("SearchWordS", searchWordS) :
                new ObjectParameter("SearchWordS", typeof(string));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Cluster_Search_SubResource", searchWordSParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_ID(Nullable<int> id, string lang, string token)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_ID", idParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<V3_Full_Resource> Proc_Get_V3_Resource_by_ID(Nullable<int> id, string lang, string token)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V3_Full_Resource>("Proc_Get_V3_Resource_by_ID", idParameter, langParameter, tokenParameter);
        }
    
        public virtual ObjectResult<SubRamResource> Proc_Get_SubResource_by_Helpline(string lang, string token)
        {
            var langParameter = lang != null ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubRamResource>("Proc_Get_SubResource_by_Helpline", langParameter, tokenParameter);
        }
    }
}
