//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MapServiceSoap")]
    public interface MapServiceSoap {
        
        // CODEGEN: Generating message contract since element name getmapenResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmapen", ReplyAction="*")]
        Web.ServiceReference1.getmapenResponse getmapen(Web.ServiceReference1.getmapenRequest request);
        
        // CODEGEN: Generating message contract since element name categories from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmapenbyCategories", ReplyAction="*")]
        Web.ServiceReference1.getmapenbyCategoriesResponse getmapenbyCategories(Web.ServiceReference1.getmapenbyCategoriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmapenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmapen", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServiceReference1.getmapenRequestBody Body;
        
        public getmapenRequest() {
        }
        
        public getmapenRequest(Web.ServiceReference1.getmapenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getmapenRequestBody {
        
        public getmapenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmapenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmapenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServiceReference1.getmapenResponseBody Body;
        
        public getmapenResponse() {
        }
        
        public getmapenResponse(Web.ServiceReference1.getmapenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmapenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getmapenResult;
        
        public getmapenResponseBody() {
        }
        
        public getmapenResponseBody(string getmapenResult) {
            this.getmapenResult = getmapenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmapenbyCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmapenbyCategories", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServiceReference1.getmapenbyCategoriesRequestBody Body;
        
        public getmapenbyCategoriesRequest() {
        }
        
        public getmapenbyCategoriesRequest(Web.ServiceReference1.getmapenbyCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmapenbyCategoriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.ServiceReference1.ArrayOfInt categories;
        
        public getmapenbyCategoriesRequestBody() {
        }
        
        public getmapenbyCategoriesRequestBody(Web.ServiceReference1.ArrayOfInt categories) {
            this.categories = categories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmapenbyCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmapenbyCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServiceReference1.getmapenbyCategoriesResponseBody Body;
        
        public getmapenbyCategoriesResponse() {
        }
        
        public getmapenbyCategoriesResponse(Web.ServiceReference1.getmapenbyCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmapenbyCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getmapenbyCategoriesResult;
        
        public getmapenbyCategoriesResponseBody() {
        }
        
        public getmapenbyCategoriesResponseBody(string getmapenbyCategoriesResult) {
            this.getmapenbyCategoriesResult = getmapenbyCategoriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MapServiceSoapChannel : Web.ServiceReference1.MapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MapServiceSoapClient : System.ServiceModel.ClientBase<Web.ServiceReference1.MapServiceSoap>, Web.ServiceReference1.MapServiceSoap {
        
        public MapServiceSoapClient() {
        }
        
        public MapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.ServiceReference1.getmapenResponse Web.ServiceReference1.MapServiceSoap.getmapen(Web.ServiceReference1.getmapenRequest request) {
            return base.Channel.getmapen(request);
        }
        
        public string getmapen() {
            Web.ServiceReference1.getmapenRequest inValue = new Web.ServiceReference1.getmapenRequest();
            inValue.Body = new Web.ServiceReference1.getmapenRequestBody();
            Web.ServiceReference1.getmapenResponse retVal = ((Web.ServiceReference1.MapServiceSoap)(this)).getmapen(inValue);
            return retVal.Body.getmapenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.ServiceReference1.getmapenbyCategoriesResponse Web.ServiceReference1.MapServiceSoap.getmapenbyCategories(Web.ServiceReference1.getmapenbyCategoriesRequest request) {
            return base.Channel.getmapenbyCategories(request);
        }
        
        public string getmapenbyCategories(Web.ServiceReference1.ArrayOfInt categories) {
            Web.ServiceReference1.getmapenbyCategoriesRequest inValue = new Web.ServiceReference1.getmapenbyCategoriesRequest();
            inValue.Body = new Web.ServiceReference1.getmapenbyCategoriesRequestBody();
            inValue.Body.categories = categories;
            Web.ServiceReference1.getmapenbyCategoriesResponse retVal = ((Web.ServiceReference1.MapServiceSoap)(this)).getmapenbyCategories(inValue);
            return retVal.Body.getmapenbyCategoriesResult;
        }
    }
}
